inherit_gem:
  jekyll: .rubocop.yml

AllCops:
  Exclude:
    - lib/jekyll-admin-josercc/public/**/*
    - src/**/*
    - node_modules/**/*
    - Gemfile
    - jekyll-admin-josercc.gemspec

Metrics/BlockLength:
  Enabled: false
